// ============================================================
// ZAPIER STEP 4 — "Code by Zapier" (JavaScript)
// ACTION: Format final output for HoneyBook update
//
// This step takes the AI outputs from Step 2 and formats them
// into clean strings ready to paste into HoneyBook's actions.
//
// INPUT FIELDS TO MAP IN ZAPIER (from Step 2):
//   summary
//   followup_message
//   missing_tasks
//   missing_tasks_count
//   extracted_client_name
//   extracted_budget
//   extracted_event_date
//   extracted_followup_status
// ============================================================

const summary = inputData.summary || "";
const followupMessage = inputData.followup_message || "";
const missingTasks = inputData.missing_tasks || "";
const missingCount = parseInt(inputData.missing_tasks_count || "0", 10);

const clientName = inputData.extracted_client_name || "";
const budget = inputData.extracted_budget || "";
const eventDate = inputData.extracted_event_date || "";
const followupStatus = inputData.extracted_followup_status || "";

const today = new Date().toLocaleDateString("en-US", {
  year: "numeric",
  month: "long",
  day: "numeric",
});

const missingTaskLines = missingTasks
  ? missingTasks.split(" | ").map(task => `• ${task}`).join("\n")
  : "";

const internalNote = [
  `AI PROJECT SUMMARY — ${today}`,
  "─".repeat(40),
  summary,
  "",
  missingCount > 0
    ? ` MISSING TASKS (${missingCount}):\n${missingTaskLines}`
    : "No missing tasks detected.",
  "",
  "SUGGESTED FOLLOW-UP MESSAGE:",
  "─".repeat(40),
  followupMessage,
  "",
  "Generated by AI Workflow Assistant",
].join("\n");

const smartFieldBlock = [
  `CLIENT:          ${clientName}`,
  `EVENT DATE:      ${eventDate}`,
  `INVESTMENT:      ${budget}`,
  `FOLLOWUP STATUS:  ${followupStatus}`,
].filter(line => !line.endsWith(":          ")).join("\n");

const statusTag = missingCount === 0
  ? "AI-Reviewed: Done"
  : `AI-Reviewed: Error - ${missingCount} Item(s) Needed`;

output = {
  honeybook_note: internalNote,
  smart_field_block: smartFieldBlock,
  project_status_tag: statusTag,
  email_body: followupMessage,
  email_subject: `Following up — ${clientName || "Your Inquiry"}`,

  field_client_name: clientName,
  field_event_date: eventDate,
  field_amount: budget,
  field_followup_status: followupStatus,

  has_missing_tasks: missingCount > 0 ? "true" : "false",
  missing_count: String(missingCount),
  missing_list: missingTasks,

  formatted_date: today,
};
